[alias]
vroom = "run --features bevy/dynamic_linking"
xtask = "run --package xtask --"
server = "run --no-default-features --features server"
mp-stop = "cmd mp-stop"
mp-win = "cmd mp-win"
mp = "cmd mp"
